esptool.py v4.8.dev4
Serial port /dev/tty.usbmodem14101

A fatal error occurred: Could not open /dev/tty.usbmodem14101, the port is busy or doesn't exist.
([Errno 2] could not open port /dev/tty.usbmodem14101: [Errno 2] No such file or directory: '/dev/tty.usbmodem14101')

Hint: Check if the port is correct and ESP connected

